#pragma once
#define NOMINMAX

// プリコンパイル済みヘッダー
#include <Windows.h>
#include <cassert>
#include <tchar.h>
#include <vector>
#include <map>
#include <unordered_map>
#include <chrono>
#include <random>
#include <algorithm>
#include <memory>
#include <string>
#include <functional>
#include <list>
#include <stack>
#include <filesystem>
#include "Utility/EngineUtility.h"
#include "Utility/ISingleton.h"